#!/bin/bash

dossier="Sprint$1"
os="$(uname)"

if [ "$os" = "Darwin" ]
then
echo "$(clang++ -g -std=c++11 -I antlr4-cpp-runtime-4/antlr4-runtime/ -o $dossier/compilo $dossier/$dossier/*.cpp antlr4-cpp-runtime-4/lib/libantlr4-runtime.a)"
elif [ "$os" = "Linux" ]
then
echo "$(clang++ -g -std=c++11 -I /usr/local/include/antlr4-runtime/ -o $dossier/compilo $dossier/$dossier/*.cpp /usr/local/lib/libantlr4-runtime.a)"
fi